2022-02-16 VT-5501 BigCommerceAccess: Add GetAllChannels method
skuvault-integrations/bigCommerceAccess pull request #20
Opened 2022-02-16 10:53 UTC by andrey-kozlov-skuvault

[VT-5501]
- Targeted project to net4.8;
- Added IBigCommerceChannelsService with the ability to get all channels with async and sync methods. Both methods are almost identical, but sync version cannot use async to avoid deadlocks when using it from e.g. ASP NET MVC. This could be addressed by adding `.ConfigureAwait(false)` for some calls (better for all awaited calls in the solution). Will be done in another PR;
- Fixed Product tests configuration and Order tests;

2022-02-16 12:04 UTC, dk-skuvault approved these changes

2022-02-16 13:05 UTC, mrassudishkin approved these changes

2022-02-18 07:34 UTC, dk-skuvault approved these changes

2022-02-18 08:40 UTC, mrassudishkin approved these changes

2022-02-18 14:54 UTC, andrey-kozlov-skuvault commented
@skuvault-integrations/core Could you please review?

2022-02-21 13:22 UTC, slav requested changes
Some comments and questions

2022-02-21 13:22 UTC, slav commented on src/BigCommerceAccessTests/Orders/OrderTests.cs
> +			Assert.Throws< Exception >( () => this.BigCommerceFactory.CreateOrdersService( config ) );
Don't catch Exception. If we're expecting WebException, catch that. If we're expecting different, catch that. If we're throwing Exception somewhere, change that to be more specific.

2022-02-21 13:22 UTC, slav commented on src/BigCommerceAccessTests/Products/ProductsTests.cs
> +				this.ConfigV2 = new BigCommerceConfig( testConfig.ShopName, testConfig.UserName, testConfig.ApiKey );
Why is this changing around? Was there a big here in the past?

2022-02-21 13:56 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/Models/Channel/BigCommerceChannelPlatform.cs
> +	public enum BigCommerceChannelPlatform
It comes from https://developer.bigcommerce.com/api-reference/store-management/channels - they have just a list of strings, which also is not accurate (some real values are missing). Just copied it from the docs, leave the order the same. They are sending strings, and we receive strings too (`PlatformStr`) - this enum is used in a calculated property for convenient work of the consumers.
I do not see the necessity for settings numbers, as:
1. ATM we just show these values on the UI in the channels list, we save only channel id.
2. Putting new value in the middle of an enum is a breaking change, you need to understand the consequences. So I would not place an item in the middle anyway. Even with assigned integer values you could also insert values in the middle and inc other values manually. Though that it will be harder to do.
So if we want to have this list sorted somehow, e.g. in alphabetical order - we could add numbers. Other than that, respecting that these values are not hardcoded codes, I do not the reason to add value in the middle.

2022-02-21 14:02 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccessTests/Orders/OrderTests.cs
> -			var orders = service.GetOrders( DateTime.UtcNow.AddMonths( -6 ), DateTime.UtcNow );
Yes, they should. 
The current fix intends to fix this problem - that tests will stop working someday. This was the problem I faced when ran them. Specific dates should be the more reliable solution IMHO - could be broken if someone intentionally deletes some orders (doubt someone would need to delete old orders) or if BC decided to archive/delete some data (not sure if is a common practice for orders, so we need to expect that).

2022-02-21 14:10 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccessTests/Orders/OrderTests.cs
> +			Assert.Throws< Exception >( () => this.BigCommerceFactory.CreateOrdersService( config ) );
The same as in previous comment

2022-02-21 14:12 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccessTests/Products/ProductsTests.cs
> +				this.ConfigV2 = new BigCommerceConfig( testConfig.ShopName, testConfig.UserName, testConfig.ApiKey );
Yes, this was a bug.
Token and API key were messed up, so incorrect config was used for product tests.
Write about it briefly in the PR description, will write in more detail.

2022-02-21 14:39 UTC, slav commented on src/BigCommerceAccess/Models/Channel/BigCommerceChannelPlatform.cs
> +	public enum BigCommerceChannelPlatform
I'm ok with it, but placing in the middle might happen again. For example since we copied it from BigCommerce docs, they might update list by adding values in the middle and when we copy the full list again they'll get added in the middle as well. But, since we don't store this enum anywhere, such as events, it's fine.

2022-02-21 14:40 UTC, slav approved these changes

2022-02-21 19:31 UTC, chris-skuvault approved these changes

2022-02-22 07:52 UTC, merged