BigCommerce MSF: Support ChannelIds for GetOrders
skuvault-integrations/bigCommerceAccess pull request #21
Opened 2022-02-16 11:08 UTC by dk-skuvault

2022-02-16 12:01 UTC, dk-skuvault commented on src/BigCommerceAccess/BigCommerceOrdersService.cs
> +				this.CreateApiDelay( ordersWithinPage.Limits ).GetAwaiter().GetResult(); //API requirement
@mrassudishkin @andrey-kozlov-skuvault what do you think should I revert this change?

2022-02-16 12:02 UTC, mrassudishkin commented on src/BigCommerceAccess/BigCommerceOrdersService.cs
> +				this.CreateApiDelay( ordersWithinPage.Limits ).GetAwaiter().GetResult(); //API requirement
I think - no

2022-02-16 13:19 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/BigCommerceOrdersService.cs
> +				this.CreateApiDelay( ordersWithinPage.Limits ).GetAwaiter().GetResult(); //API requirement
I'm ok with this. Maybe it is something we should add to [VT-5508] too.

2022-02-16 13:32 UTC, andrey-kozlov-skuvault approved these changes

2022-02-21 08:54 UTC, mrassudishkin approved these changes

2022-02-23 04:03 UTC, slav reviewed
had a couple of comments

2022-02-23 04:03 UTC, slav commented on src/BigCommerceAccess/Services/ParamsBuilder.cs
> +			var endpoint = $"?{BigCommerceParam.OrdersModifiedDateFrom.Name}={startDateUtc:o}" +
why not just return string? endpoint here is invalid terminology. You're forming parameters for GET request, not endpoint URL

2022-02-23 04:03 UTC, slav commented on src/BigCommerceAccessTests/BigCommerceTestsBase.cs
> +	public class BigCommerceTestsBase
Should this maybe be a helper class instead of base class? I know in many cases right now we use this pattern, but not sure if that's the best approach to pull common logic like this into base and not helper? What do you think?

2022-02-23 08:43 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccessTests/BigCommerceTestsBase.cs
> +	public class BigCommerceTestsBase
In this case, I do not have problems with having a Base class for the tests. We have `[ OneTimeSetUp ]` method, common for all tests. Config methods could be moved away, but I do not see a real need for this here.

2022-02-23 08:55 UTC, dk-skuvault commented on src/BigCommerceAccess/Services/ParamsBuilder.cs
> +			endpoint = $"{endpoint}&{BigCommerceParam.ChannelId.Name}={channelId}";
renamed

2022-02-23 08:56 UTC, dk-skuvault commented on src/BigCommerceAccess/Services/ParamsBuilder.cs
> +			var endpoint = $"?{BigCommerceParam.OrdersModifiedDateFrom.Name}={startDateUtc:o}" +
renamed

2022-02-23 08:59 UTC, dk-skuvault commented on src/BigCommerceAccessTests/BigCommerceTestsBase.cs
> +	public class BigCommerceTestsBase
I think in this specific case base class is ok. I don't know which benefits we can get using helpers instead.

2022-03-01 19:21 UTC, reydelleon-skuvault requested changes

2022-03-01 19:21 UTC, reydelleon-skuvault commented on src/BigCommerceAccessTests/BigCommerceAccessTests.csproj
> +  </Target>
Should this condition be so specific? What happens if we upgrade?

2022-03-02 08:07 UTC, dk-skuvault commented on src/BigCommerceAccessTests/BigCommerceAccessTests.csproj
> +  </Target>
@reydelleon-skuvault It was added automatically while updating NUnit package with Rider. I tried to revert my changes and reupdate it with Visual Studio but it was done in the same way. Do you think I have to remove this code?

2022-03-02 13:51 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccessTests/BigCommerceAccessTests.csproj
> +  </Target>
removed

2022-03-02 14:20 UTC, reydelleon-skuvault approved these changes

2022-03-02 14:25 UTC, merged