2022-02-16 VT-5495 BigCommerce MSF: Update Product Pull in SV
skuvault-integrations/bigCommerceAccess pull request #22
Opened 2022-02-16 11:58 UTC by mrassudishkin

[VT-5495]
Updated product pull for MSF

2022-02-16 13:05 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV3.cs
> +				await this.CreateApiDelay( productsChannelAssignmentsWithinPage.Limits, token ); //API requirement
ConfigureAwait is missing

2022-02-16 13:05 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV3.cs
> +							marker ) );
ConfigureAwait is missing

2022-02-16 13:05 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccessTests/Products/ProductsTests.cs
> +
Also, I think it would be great to add some tests on getting products e.g. get products and assignments for channel 1, and ensure that all the products are in assignments, and no other products returned.

2022-02-16 15:46 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV3.cs
> +			return channelIds != null && !channelIds.Any()
Though it is from StackExchange library. Maybe we can do an extension like this ourselves.

2022-02-17 08:25 UTC, dk-skuvault commented on src/BigCommerceAccess/Models/Product/BigCommerceProductChannelAssignmentInfoData.cs
> +		[ DataMember( Name = "data" ) ] public List< BigCommerceProductChannelAssignment > Data{ get; set; }
Can you move attribute to separate line? I fixed R# settings in my branch to do it automatically

2022-02-17 08:33 UTC, dk-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV2.cs
> +				throw new Exception( "You can use channels filtration (MSF feature) only with BigCommerce API V3, which requires token authentication." );
Hmm I didn't add any exceptions in orders service for case if you pass channelIds together with old credentials. If it happens I just skip filtration and it works as before. Do you think we should throw exception in that case?

2022-02-17 08:35 UTC, dk-skuvault commented on src/BigCommerceAccess/IBigCommerceProductsService.cs
> +		List< BigCommerceProductChannelAssignment > GetProductsChannelAssignments( List< long > channelIds );
Should we do this method as public? Will we use it in SV?

2022-02-17 08:36 UTC, dk-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV3.cs
> +		/// Get product assignments is a GET request, so we have 2048 chars in URL limitation. one product id of type long is at maximum of 20 chars, so we should be able to request 80 products in one requ
This comment looks soo long. Can you brake down it in two lines?

2022-02-17 08:44 UTC, dk-skuvault commented on src/BigCommerceAccess/IBigCommerceProductsService.cs
> +		List< BigCommerceProduct > GetProducts( bool includeExtendInfo = false, List< long > channelIds = null );
Should channelIds be optional parameter? If we do it so we have a chance to miss passing channels to access lib but as I know we don't have any place in V1 code when it should not be passed. I think we can do it as required but it can accept nulls.

2022-02-17 08:47 UTC, dk-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV3.cs
> +				} ).Get( async () =>
We decided to not change existing methods. Do you reuse this method in static context? Or why did you change it?

2022-02-17 08:48 UTC, dk-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV3.cs
> +						.ConfigureAwait( false ) );
We decided to not change existing methods. Do you reuse this method in static context? Or why did you change it?

2022-02-17 08:50 UTC, dk-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV3.cs
> +			return this.GetProductsChannelAssignmentsAsync( CancellationToken.None, channelIds ).GetAwaiter().GetResult();
We decided to copy-paste code. Why do you reuse it?

2022-02-17 08:51 UTC, dk-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV3.cs
> +			var mainEndpoint = "?channel_id:in=" + string.Join( ",", channelIds );
Can you move it to ParamsBuilder?

2022-02-17 08:56 UTC, dk-skuvault commented on src/BigCommerceAccess/IBigCommerceProductsService.cs
> +		List< BigCommerceProduct > GetProducts( bool includeExtendInfo = false, List< long > channelIds = null );
Do you have deduplication for channelIds? In orders service I changed it to HasSet by this reason.

2022-02-17 08:57 UTC, dk-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV3.cs
> +					.ConcatParams( ParamsBuilder.CreateGetNextPageParams( new BigCommerceCommandConfig( 1, ProductAssignmentBatchSize ) ) )
can you move it to ParamsBuilder?

2022-02-17 08:57 UTC, dk-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV3.cs
> +			var mainEndpoint = "?include=variants,images";
can you move it to ParamsBuilder?

2022-02-17 09:38 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/IBigCommerceProductsService.cs
> +		List< BigCommerceProductChannelAssignment > GetProductsChannelAssignments( List< long > channelIds );
Not right now, but if we would save assignments in SV. I think it is ok to have it as `public` here. Maybe we need to add tests for it in that case

2022-02-17 13:31 UTC, mrassudishkin commented on src/BigCommerceAccess/BigCommerceProductsServiceV2.cs
> +				throw new Exception( "You can use channels filtration (MSF feature) only with BigCommerce API V3, which requires token authentication." );
> Hmm I didn't add any exceptions in orders service for case if you pass channelIds together with old credentials. If it happens I just skip filtration and it works as before. Do you think we should throw exception in that case?

I thought yes so made it :)

2022-02-21 09:44 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV3.cs
> +		private Uri CreateUrlProductsIn( string endpoint, Queue< long > commonQueueProductIds, Queue< long > queueProductIdsForRequest )
Could you describe this logic? You try to add a full portion, and remove id one by one if Uri is invalid? I think this method should be moved to some builder (or to the existing ParamsBuilder) and should be unit tested separately, as it is a new method with complex logic.

2022-02-21 09:44 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccessTests/Products/ProductsTests.cs
> +		public void GetProductsByChannels( BigCommerceConfigVersion configVersion )
Need better name according to our unit test name template `MethodName_Outcome_Context` [link to rules](https://agileharbor.atlassian.net/wiki/spaces/DEV/pages/3108208699/Unit+Tests+standards), e.g. `GetProducts_ReturnsOnlySpecificChannelProducts`.
I think all the tests could be renamed, as if we change almost all.

2022-02-21 09:44 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccessTests/Products/ProductsTests.cs
> +			foreach( var product in products )
Maybe better to use [EquivalentTo](https://docs.nunit.org/articles/nunit/writing-tests/constraints/CollectionEquivalentConstraint.html) for this assertion - it also checks item count.

2022-02-21 09:44 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV3.cs
> +		private Uri CreateUrlProductsIn( string endpoint, Queue< long > commonQueueProductIds, Queue< long > queueProductIdsForRequest )
Also, this method not only creates an Url, but also moves elements between the queues. I think this method should be separated, as these are 2 different responsibilities - e.g. one shows how many elements we need to move back  and maybe out URL, the other is to perform move between queues.

2022-02-21 09:44 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV3.cs
> +				commonQueueProductIds.Enqueue( queueProductIdsForRequest.Dequeue() );
That way first element we need to get will be moved back to the waiting queue. Not sure it is vary important for us here, but still looks strange. Maybe we could to use stack then for the buffer to queue?

2022-02-21 09:44 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV3.cs
> +			var commonQueueProductIds = new Queue< long >( productIds );
Maybe better to name queues `remainingProductIdsToGet` and `productIdsForCurrentRequest`. No need to add a type `queue` to the name.

2022-02-21 09:44 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV3.cs
> +		private void MoveItemsBetweenQueues< T >( Queue< T > from, Queue< T > to, int count )
Maybe make these methods extensions methods? And e.g. place to `Misc\QueueExtensions`. They will be easier to read and use. And better to have them unit tested - at least one simple test for every method.

2022-02-21 12:00 UTC, dk-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV3.cs
> +								this.MoveItemsBetweenQueues( commonQueueProductIds, queueProductIdsForRequest, countItemsInRequest );
I think this logic is too complicated and the main issue is that you need to move items back to the initial collection on failed requests.

As an alternate way, you could remove items from the initial collection only after the success call. 
- So you will have a single collection with products ids
- Before the call, you will take first N products
- Then you check that URL is correct (max length check). If false then you will try to reduce N and check again.
- Finally, you will have URL and N products you are trying to get. I think N is countItemsInRequest.
- Do call.
- After the call you will remove N products from the initial collection with products ids. 
- Go to next loop iteration

So in .Retry method you will update countItemsInRequest variable only. But the main logic will be in .Get method. And you will have only one collection with product id and you don't need to move ids between collections.

2022-02-21 12:15 UTC, dk-skuvault commented on src/BigCommerceAccessTests/Products/ProductsTests.cs
> +			var products = service.GetProducts( null, true );
We pass true here but did check that we actually receive ExtendInfo. I think this test should be renamed to something like GetProducts_ProductsWithExtendedInfoReceived_WhenExtendInfoRequested

2022-02-21 12:18 UTC, dk-skuvault commented on src/BigCommerceAccessTests/Products/ProductsTests.cs
> +			var products = service.GetProducts( null );
We pass false here but did check that we actually DIDN'T receive ExtendInfo. I think this test should be renamed to something like GetProducts_ProductsWithoutExtendedInfoReceived_WhenExtendInfoNotRequested

And in this test you will check that we don't get ExtendInfo but we check other information (I giess it's inventory information)

2022-02-21 12:26 UTC, dk-skuvault commented on src/BigCommerceAccessTests/Products/ProductsTests.cs
> +			var productsChannelAssignments = await service.GetProductsChannelAssignmentsAsync( CancellationToken.None, new HashSet< long > { 1 } );
Would be cool to see more tests with edge cases.  For example if product is not assigned to default channel or product assigned on two channels or product is not assigned to any channel

2022-02-21 13:49 UTC, mrassudishkin commented on src/BigCommerceAccessTests/Products/ProductsTests.cs
> +			foreach( var product in products )
I did so because productsChannelAssignments can have productId but request GetProducts doesn't return this product. So I can't use EquivalentTo here

2022-02-22 09:15 UTC, dk-skuvault requested changes

2022-02-22 09:15 UTC, dk-skuvault commented on src/BigCommerceAccess/Services/ParamsBuilder.cs
> +		public static int CalculateNumberOfIdsInOneRequest( int lengthCurrentRequest, int maxLengthRequestWithIds, int maxNumberItemsInRequest, List< long > ids )
Maybe would be better to change signature to something like this:
GetIdsCountForRequest( int currentUrlLength, int maxUrlLength, int maxIdsCountInRequest, List< long > remainingIds )

Also maxUrlLength is constant we keep in BigCommerceProductsServiceV3. Maybe we can move it to ParamsBuilder.

2022-02-22 09:15 UTC, dk-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV3.cs
> +			var maxNumberItemsInRequest = this.RequestMaxLimit;
maybe maxProductIdsCountInRequest?

2022-02-22 09:15 UTC, dk-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV3.cs
> +							maxNumberItemsInRequest = factNumberItemsInRequest;
Maybe we can change factNumberItemsInRequest to productIdsCountInRequest

2022-02-22 09:22 UTC, dk-skuvault commented on src/BigCommerceAccessTests/Products/ProductsTests.cs
> +			productWithWeightUnitOrBrandName.Count().Should().BeGreaterThan( 0 );
I guess that all products should be with Weight and Brand. Can it be missed even if we request this info?

2022-02-22 09:26 UTC, dk-skuvault commented on src/BigCommerceAccessTests/Products/ProductsTests.cs
> +			productsChannelAssignments.All( x => x.ChannelId == 1 );
![image](https://user-images.githubusercontent.com/81695104/155102600-6af4f36d-f15d-4065-b4c6-423586da2277.png)

2022-02-22 10:03 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccessTests/Misc/ParamsBuilderTests.cs
> +			var expectedNumberIds =( maxLengthRequestWithIds - lengthCurrentRequest ) / ( StartId.ToString().Length + 1 );
We should not use such complex formulas in tests. Need to have a specific value instead, as stated [here](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#avoid-logic-in-tests)

2022-02-22 10:03 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccessTests/Misc/ParamsBuilderTests.cs
> +		private const long StartId = 6939004534535;
PLease describe why you choose this value, as stated [here](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#avoid-magic-strings) (no it looks like a magic string)

2022-02-22 10:03 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccessTests/Products/ProductsTests.cs
> +			foreach( var product in products )
Do we have an example of this? Because some products could be deleted?

2022-02-22 11:20 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccessTests/Products/ProductsTests.cs
> +			foreach( var product in products )
Ah, maybe some products could be returned as variants? Maybe we could check this then - that we have whether product or variation for every id in assignments.

2022-02-22 11:20 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccessTests/Products/ProductsTests.cs
> +		{
GetProducts_ReturnsProductsWhichDoesNot**Belong**ToAnyChannels

2022-02-22 11:20 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccessTests/Products/ProductsTests.cs
> +			Assert.That( productsChannelAssignments.Count, Is.Not.EqualTo( products.Count ) );
Not sure this assertion proves that we return a product that is not tied to any channel. Maybe better to check that there is a product returned that could not be found in assignments?
Something like this, if assignments also contains options (variations):
```
			Assert.True( products.Any(product => !productsChannelAssignments.Any(assignment => assignment.ProductId == product.Id) || // for products
			                              product.ProductOptions.Any(option => !productsChannelAssignments.Any(assignment => assignment.ProductId == option.Id))) // for options/variations
			); 
```

2022-02-22 14:18 UTC, dk-skuvault approved these changes

2022-02-23 09:51 UTC, andrey-kozlov-skuvault approved these changes

2022-02-23 12:16 UTC, dk-skuvault approved these changes

2022-03-01 19:10 UTC, reydelleon-skuvault requested changes
There are some general concerns here and I have left comments throughout the code to address them.

2022-03-01 19:10 UTC, reydelleon-skuvault commented on src/BigCommerceAccessTests/Misc/ParamsBuilderTests.cs
> +			}
Can we use `Range()` here to make this shorter. See https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.range?redirectedfrom=MSDN&view=net-6.0#System_Linq_Enumerable_Range_System_Int32_System_Int32_
We wouldn't need to even create the `StartingId `const.

2022-03-01 19:10 UTC, reydelleon-skuvault commented on src/BigCommerceAccessTests/Products/ProductsTests.cs
> +			productWithWeightUnitOrBrandName.Count().Should().BeGreaterThan( 0 );
Is this resolved?

2022-03-02 06:25 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV2.cs
> +				throw new Exception( "You can use channels filtration (MSF feature) only with BigCommerce API V3, which requires token authentication." );
Yep, we have this task in https://agileharbor.atlassian.net/browse/VT-5517 for the whole project.
Probably these new exceptions could be changed in this PR, as Reydel proposed.

2022-03-02 12:54 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccessTests/Misc/ParamsBuilderTests.cs
> +			}
We need to use `long` numbers here, and it seems that we do not have such overload.

2022-03-02 13:04 UTC, mrassudishkin commented
> There are some general concerns here and I have left comments throughout the code to address them.

Fixed

2022-03-02 14:21 UTC, mrassudishkin commented on src/BigCommerceAccess/BigCommerceProductsServiceV2.cs
> +				throw new Exception( "You can use channels filtration (MSF feature) only with BigCommerce API V3, which requires token authentication." );
Fixed type of exception

2022-03-02 14:22 UTC, mrassudishkin commented on src/BigCommerceAccess/BigCommerceProductsServiceV2OAuth.cs
> +				throw new Exception( "You can use channels filtration (MSF feature) only with BigCommerce API V3, which requires token authentication." );
Fixed

2022-03-02 14:22 UTC, mrassudishkin commented on src/BigCommerceAccess/BigCommerceProductsServiceV2OAuth.cs
> +				throw new Exception( "You can use channels filtration (MSF feature) only with BigCommerce API V3, which requires token authentication." );
Fixed

2022-03-02 14:24 UTC, mrassudishkin commented on src/BigCommerceAccess/BigCommerceProductsServiceV2OAuth.cs
> +		}
Because we don't handle it for V2 BigCommerce. We want to remove this service in phase 2

2022-03-02 15:23 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV2OAuth.cs
> +		}
Used `NotImplementedException`

2022-03-02 15:24 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/BigCommerceProductsServiceV2.cs
> +		}
Used `NotImplementedException`

2022-03-02 16:02 UTC, reydelleon-skuvault approved these changes

2022-03-02 17:07 UTC, merged