2022-03-29 VT-5524 Rework getting products to get products and variation independently
skuvault-integrations/bigCommerceAccess pull request #31
Opened 2022-03-29 13:49 UTC by mrassudishkin

[VT-5524]
- Removed variants from request GetProducts
- Added separate request for variants. This request works by ids.
- Updated unit tests and integration tests

2022-03-30 16:20 UTC, andrey-kozlov-skuvault requested changes

2022-03-30 16:20 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/ApiServices/ProductsApiService.cs
> +		Task< BigCommerceResponse< BigCommerceVariants > > GetProductsVariantsAsync(
Don't we have an ability for pagination? As I know there is a possibility, it is v3 API. Without pagination the problem with exceeding response limit may occur again, so this change makes nothing to solve the problem. Then main idea of all these changes is to use pagination for getting variations.

2022-03-30 16:20 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/ApiServices/ProductsApiService.cs
> +			return await this._webRequestServices.GetResponseAsync< BigCommerceVariants >(
I think we need to include `include_fields` in the query to limit the count of requested fields - we do not use all returned fields, as I understand, according to https://developer.bigcommerce.com/api-reference/b3A6MzU5MDQzODM-get-all-variants

2022-03-31 09:30 UTC, mrassudishkin commented on src/BigCommerceAccess/ApiServices/ProductsApiService.cs
> +			return await this._webRequestServices.GetResponseAsync< BigCommerceVariants >(
Added

2022-03-31 11:28 UTC, andrey-kozlov-skuvault approved these changes

2022-03-31 11:44 UTC, dk-skuvault approved these changes

2022-04-01 05:45 UTC, merged