2022-04-01 MSF Phase 2 - General refactoring BigCommerce
skuvault-integrations/bigCommerceAccess pull request #32
Opened 2022-04-01 12:07 UTC by mrassudishkin

2022-04-04 06:51 UTC, dk-skuvault approved these changes

2022-04-07 01:57 UTC, slav requested changes
* Left inline comments
* A lot of empty whitespace at the end of lines formatting issues. Maybe reformat project?
* We'll need to switch to the other way to reference nuget packages (in csproj). Could do when switching projects to .net standard 2.0

2022-04-07 01:57 UTC, slav commented on src/BigCommerceAccessTests/IntegrationTests/ChannelsIntegrationTests.cs
> +	[ SuppressMessage( "Performance", "ASYNC0004:Use ConfigureAwait(false) on await expression" ) ]
Why not just add this at tests project csproj level?

2022-04-07 01:57 UTC, slav commented on src/BigCommerceAccessTests/Misc/PaginationTests.cs
> +		public void GetDataPagesAsync_WhenNumberOfItemsIsLesserThanPageSize()
Did you mean to say Smaller? I'm not sure if Lesser is a real word.

2022-04-07 01:57 UTC, slav commented on src/BigCommerceAccessTests/Misc/PaginationTests.cs
> +			var data = PaginationUtil.GetDataByPagesAsync(
Why not make this test async and then await for the data?

2022-04-07 01:57 UTC, slav commented on src/BigCommerceAccessTests/Misc/RetryPolicyTests.cs
> +			logger.Received( maxRetryAttempts ).LogRetryException(
Are the parameters really different from one run to the next? We should try to provide specific expected parmaeters when we can, and use Any if we it changes from run to run and we cannot determine what it is. Otherwise we're missing part of the test, don't we?

2022-04-07 01:57 UTC, slav commented on src/BigCommerceAccessTests/Misc/RetryPolicyTests.cs
> +				.ExecuteAsync( async () => {
Does the part inside ExecuteAsync the same frome one test to the next? Should we refactor it to a common method we call?

2022-04-07 01:57 UTC, slav commented on src/BigCommerceAccessTests/UnitTests/OrdersUnitTests.cs
> +		public new void Init()
This is very complicated setup and hard to follow. There're several options:
* Pull out to separate methods, each with good name
* Leave inline // Comment describing what each setup does

Both approaches aim to make it clear (document) what you intend the code to do.

2022-04-07 01:57 UTC, slav commented on src/BigCommerceAccessTests/UnitTests/OrdersUnitTests.cs
> +		public async Task GetOrdersAsync_ReturnsAllOrders_WhenWeUseV2Service()
Looking at this I've no idea why it works this way, and if it breaks, why it broke or how to fix. Why are we getting received 1, 1, then 2, 2? Is it because it was setup that way?

2022-04-07 01:57 UTC, slav commented on src/BigCommerceAccessTests/UnitTests/ProductsUnitTests.cs
> +		public new void Init()
Again, can we document setup a little bit to make it clearer?

2022-04-07 05:34 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccessTests/Misc/PaginationTests.cs
> +		public void GetDataPagesAsync_WhenNumberOfItemsIsLesserThanPageSize()
"Lesser" is a real word, but we should use "Less" here because we are talking about quantity here, not quality.
https://english.stackexchange.com/questions/24719/difference-between-less-and-lesser

2022-04-07 05:51 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/Infrastructure/RetryPolicy.cs
> +				.OrResult( response => ( int )response.StatusCode >= 500
I think no, because here we are working with custom class `TResult : IBigCommerceResponse`, not with ``HttpResponseMessage` for which we have extensions: https://github.com/App-vNext/Polly.Extensions.Http/blob/master/src/Polly.Extensions.Http/HttpPolicyExtensions.cs#L43.
And we also extended transient errors with 429 status code, so there will be additional OrResult() anyway

2022-04-08 12:51 UTC, andrey-kozlov-skuvault approved these changes

2022-04-08 14:06 UTC, slav commented on src/BigCommerceAccess/ProductsService.cs
> -	abstract class BigCommerceBaseProductsService : BigCommerceServiceBase
Didn't understand the class. Perhaps should be named then BigCommerceProductsServiceBase, similar to it's parent class?

2022-04-08 14:08 UTC, slav commented on src/BigCommerceAccess/Infrastructure/RetryPolicy.cs
> +				.WaitAndRetryAsync( Backoff.ExponentialBackoff( TimeSpan.FromMilliseconds( DelayIncrementInMs ), this.RetryAttempts ),
So what's the maximum delay we can get here? And what's total amount of time until we fail?

2022-04-08 14:09 UTC, slav commented on src/BigCommerceAccess/Infrastructure/RetryPolicy.cs
> +				.WaitAndRetryAsync( Backoff.ExponentialBackoff( TimeSpan.FromMilliseconds( DelayIncrementInMs ), this.RetryAttempts ),
Also, is it possible to provide cancellation token to backoff? Imagine we're trying to shut down cijobs, and here it's not allowing it to shut down because it keeps retrying.... Can we interrupt retries somehow?

2022-04-08 14:10 UTC, slav requested changes
Asked a couple of inline comments and to potentially add cancellation on retries, in case we're trying to shut down

2022-04-08 18:01 UTC, chris-skuvault requested changes

2022-04-08 18:01 UTC, chris-skuvault commented on src/BigCommerceAccess/Infrastructure/RetryPolicy.cs
> +	public sealed class RetryPolicy
Lets name this appropriate as its only used for Http related retries. Something like HttpRetryPolicy might make more sense.

2022-04-09 14:59 UTC, slav commented on src/BigCommerceAccess/Infrastructure/RetryPolicy.cs
> +		internal async Task< TResult > ExecuteAsync< TResult >(
This and other comments will be irrelevant when we switch to ihttpclient factory with DI where polly rules are registered with the client factory in DI container.

2022-04-11 08:35 UTC, mrassudishkin commented on src/BigCommerceAccess/Infrastructure/RetryPolicy.cs
> +				.WaitAndRetryAsync( Backoff.ExponentialBackoff( TimeSpan.FromMilliseconds( DelayIncrementInMs ), this.RetryAttempts ),
Added comment. 1000, 2000, 4000, 8000, 16000
I can't find way send CancellationToken to WaitAndRetryAsync.

2022-04-12 06:38 UTC, merged