2022-04-07 VT-5530 Get rid of Netco
skuvault-integrations/bigCommerceAccess pull request #33
Opened 2022-04-07 11:38 UTC by mrassudishkin

[VT-5530]
Update ILogger and removed Netco, but added Netco.Tasks

2022-04-07 16:37 UTC, dk-skuvault commented on src/BigCommerceAccess/BigCommerceAccess.csproj
> +      <HintPath>..\packages\System.Buffers.4.5.1\lib\net461\System.Buffers.dll</HintPath>
Uh so much new references. Which package you installed that they were added?

2022-04-08 06:34 UTC, mrassudishkin commented on src/BigCommerceAccess/BigCommerceAccess.csproj
> +      <HintPath>..\packages\System.Buffers.4.5.1\lib\net461\System.Buffers.dll</HintPath>
Checked. Microsoft.Extensions.Logging

2022-04-08 06:47 UTC, dk-skuvault commented on src/BigCommerceAccess/Misc/EnumExtensions.cs
> -			new Logger().LogError( $"[bigCommerce]\tCan't parse enum value {value} for type {typeof( T )}" );
With this log we want to know when new values added on BC side. So these logs will indicate that we have to update our enum.

But even if we don't want to log this certain place we plan to use this approach for all integrations. So I want to note that we don't have a way to whire logs in static context. Right? Are we all agree with this approach? Should we investigate this problem and try to find a way to write logs in such cases or it will be separate ticket?

2022-04-08 06:48 UTC, dk-skuvault commented on src/BigCommerceAccess/Misc/EnumExtensions.cs
> -			new Logger().LogError( $"[bigCommerce]\tCan't parse enum value {value} for type {typeof( T )}" );
@skuvault-integrations/redalert @slav

2022-04-08 12:27 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccessTests/IntegrationTests/ProductsIntegrationTests.cs
> +using Netco.Logging;
Why we want to add Netco here?

2022-04-08 12:31 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/Misc/EnumExtensions.cs
> -			new Logger().LogError( $"[bigCommerce]\tCan't parse enum value {value} for type {typeof( T )}" );
I think in places when we really need logging - we should have an ability to pass it, e.g. static methods or utils. So here we could pass logger to the ToEnum method.

2022-04-08 12:32 UTC, andrey-kozlov-skuvault approved these changes
In general I'm ok with this, small comment on using Netco.Logging in tests

2022-04-08 12:45 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/BigCommerceAccess.csproj
> +      <HintPath>..\packages\System.Buffers.4.5.1\lib\net461\System.Buffers.dll</HintPath>
So these references are added even when installing package in VS, not only in Rider, right?

2022-04-08 13:14 UTC, mrassudishkin commented on src/BigCommerceAccess/BigCommerceAccess.csproj
> +      <HintPath>..\packages\System.Buffers.4.5.1\lib\net461\System.Buffers.dll</HintPath>
yes

2022-04-08 13:26 UTC, mrassudishkin commented on src/BigCommerceAccess/Misc/EnumExtensions.cs
> -			new Logger().LogError( $"[bigCommerce]\tCan't parse enum value {value} for type {typeof( T )}" );
@andrey-kozlov-skuvault How can I send logger to field of class ? For example:
public BigCommerceChannelStatus Status => this.StatusStr.ToEnum< BigCommerceChannelStatus >( ????? );

2022-04-09 09:15 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/Misc/EnumExtensions.cs
> -			new Logger().LogError( $"[bigCommerce]\tCan't parse enum value {value} for type {typeof( T )}" );
It could be done as `public BigCommerceChannelStatus Status(ILogger logger = null) => this.StatusStr.ToEnum< BigCommerceChannelStatus >(logger);`
If we really need logger in static contexts (which we should avoid in general) - then yep, we need to save it in a static way somewhere. One place we could do this could be the place when we registering logging system for a big commerce - there we could set some module static variable when registering. This could be discussed with the core. Though here not sure we really need it.

2022-04-11 10:49 UTC, mrassudishkin commented on src/BigCommerceAccess/Misc/EnumExtensions.cs
> -			new Logger().LogError( $"[bigCommerce]\tCan't parse enum value {value} for type {typeof( T )}" );
Ok. Done

2022-04-12 01:42 UTC, slav commented on src/BigCommerceAccess/BigCommerceAccess.csproj
> +    <Reference Include="Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60">
Do you really need this package? Is just Microsoft.Extensions.DependencyInjection.Abstractions not enough? Why not?

2022-04-12 01:43 UTC, slav commented on src/BigCommerceAccess/BigCommerceAccess.csproj
> +    <Reference Include="Microsoft.Extensions.Logging, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60">
Do you really need this package? Is just Microsoft.Extensions.Logging.Abstractions not enough? Why?

2022-04-12 01:44 UTC, slav requested changes
In the main access library should only need to add nuget packages with abstractions for logging and DI. Don't need concrete implementations. Those would be in the calling code (such as tests or cijobs). Try to remove un-needed dependencies.

2022-04-12 08:52 UTC, mrassudishkin commented on src/BigCommerceAccess/BigCommerceAccess.csproj
> +    <Reference Include="Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60">
Removed.

2022-04-12 08:52 UTC, mrassudishkin commented on src/BigCommerceAccess/BigCommerceAccess.csproj
> +    <Reference Include="Microsoft.Extensions.Logging, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60">
Removed

2022-04-12 08:53 UTC, mrassudishkin commented
> In the main access library should only need to add nuget packages with abstractions for logging and DI. Don't need concrete implementations. Those would be in the calling code (such as tests or cijobs). Try to remove un-needed dependencies.

I removed them, but I didn't install these packages specially. It was install automatically.

2022-04-12 11:55 UTC, dk-skuvault approved these changes

2022-04-14 06:24 UTC, merged