2022-04-07 VT-5531 Use System.Text.Json instead of ServiceStack and Newtonsoft.Json
skuvault-integrations/bigCommerceAccess pull request #35
Opened 2022-04-07 11:47 UTC by mrassudishkin

[VT-5531]
Removed Newtonsoft.Json
Added System.Text.Json

2022-04-07 16:54 UTC, dk-skuvault commented on src/BigCommerceAccess/Misc/DateTimeConverter.cs
> +		public override DateTime Read( ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options )
@slav are we sure we want to use System.Text.Json? Doesn't look it work out from box even in such simple cases.

2022-04-07 17:00 UTC, dk-skuvault commented on src/BigCommerceAccess/Services/WebRequestServices.cs
> +					var result = JsonSerializer.Deserialize< T >( jsonResponse, options );
Is it possible to set these options globally but not before each deserialization?

2022-04-08 08:18 UTC, mrassudishkin commented on src/BigCommerceAccess/Services/WebRequestServices.cs
> +					var result = JsonSerializer.Deserialize< T >( jsonResponse, options );
Added extension. That's ok? Seems like this library doesn't have more globally initialize options.

2022-04-08 08:46 UTC, dk-skuvault commented on src/BigCommerceAccess/Services/WebRequestServices.cs
> +					var result = JsonSerializer.Deserialize< T >( jsonResponse, options );
I don't like doing that but looks like we don't have another way with System.Text.Json

2022-04-08 08:52 UTC, dk-skuvault commented on src/BigCommerceAccess/Misc/DateTimeConverter.cs
> +		public override DateTime Read( ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options )
Maybe we have to look to Utf8Json

2022-04-08 12:46 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/BigCommerceAccess.csproj
> +    <NuGetPackageImportStamp>
What is this for?

2022-04-08 12:46 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/app.config
> +﻿<?xml version="1.0" encoding="utf-8"?>
Looks like nuget package was installed in Rider, is it correct?
As app.config does not usually appear when installing package from VS.

2022-04-08 12:46 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/Misc/BigCommerceJsonSerializer.cs
> +				new JsonStringEnumConverter( JsonNamingPolicy.CamelCase ),
Could you describe why we need this converters, e.g. individually in comments?

2022-04-08 12:46 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/Misc/DateTimeConverter.cs
> +		public override DateTime Read( ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options )
Need to comment this class - what it does and why it is needed, and the others

2022-04-08 12:55 UTC, mrassudishkin commented on src/BigCommerceAccess/app.config
> +﻿<?xml version="1.0" encoding="utf-8"?>
Correct. Do you want that I remove it?

2022-04-08 13:08 UTC, andrey-kozlov-skuvault commented on src/BigCommerceAccess/app.config
> +﻿<?xml version="1.0" encoding="utf-8"?>
I would try to install package in VS from the scratch. Maybe there will be less changes, as I faced this problem before. Rider adds more updates to the references than VS.

2022-04-08 15:36 UTC, slav commented on src/BigCommerceAccess/Misc/DateTimeConverter.cs
> +		public override DateTime Read( ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options )
@dk-skuvault yes, we want to use that. It's MS standard library.

2022-04-08 15:41 UTC, slav commented on src/BigCommerceAccess/Misc/DateTimeConverter.cs
> +		public override DateTime Read( ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options )
It looks like System.Text.Json supports DateTime serialization: https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support - so I'd like to understand why we need to develop custom one here

2022-04-08 15:54 UTC, slav requested changes
Some inline comments

2022-04-08 15:54 UTC, slav commented on src/BigCommerceAccess/app.config
> +﻿<?xml version="1.0" encoding="utf-8"?>
Yes, we probably don't want this

2022-04-08 15:54 UTC, slav commented on src/BigCommerceAccess/Services/WebRequestServices.cs
> +					var result = jsonResponse.Deserialize< T >();
If people don't like extension method, maybe just use BigCommerceJson.Deserialize or something like that? So you still call method, just not through extension? Just a thought.

2022-04-08 15:54 UTC, slav commented on src/BigCommerceAccess/packages.config
> +  <package id="System.Diagnostics.DiagnosticSource" version="5.0.0-preview.7.20364.11" targetFramework="net48" />
Can we use stable version here?

2022-04-08 15:54 UTC, slav commented on src/BigCommerceAccessTests/app.config
> +<configuration>
Is this file necessary?

2022-04-12 08:53 UTC, dk-skuvault approved these changes

2022-04-12 11:01 UTC, mrassudishkin commented on src/BigCommerceAccess/Misc/NullableDecimalConverter.cs
> +	public class NullableDecimalConverter: JsonConverter< decimal? >
I added it because we can't deserialize response from BigCommerce without it.

2022-04-12 11:01 UTC, mrassudishkin commented on src/BigCommerceAccess/Services/WebRequestServices.cs
> +
Removed

2022-04-14 13:54 UTC, slav approved these changes

2022-04-15 06:05 UTC, merged